### ISSUE TITLE
Update `json-patch` to 2.0.0

### ISSUE THREAD

**Issue by clux** [kube-rs/kube#1503]
Failing finalizer helper stuff via dependabot ignored PR in https://github.com/kube-rs/kube/pull/1493.

Seems to want different types for patch operations. Many errors like:

```
error[E0308]: mismatched types
   --> kube-runtime/src/finalizer.rs:144:68
    |
144 |                     PatchOperation::Remove(RemoveOperation { path: finalizer_path }),
    |                                                                    ^^^^^^^^^^^^^^ expected `Pointer`, found `String`
```

See https://github.com/idubrov/json-patch (the changelog is out of date, and no release notes afaikt).

Don't have time to look at it now so leaving it open. Would be good to tackle because people might confuse it with a kube problem that finalizer api does not work if they are able to build with multiple deps ala https://github.com/kube-rs/kube/issues/1490.
