### ISSUE TITLE
Upgrade to hashbrown 0.15.0

### ISSUE THREAD

**Issue by clux** [kube-rs/kube#1597]
Failed CI in https://github.com/kube-rs/kube/pull/1591 at kube-runtime with:

```
error[E0599]: no method named `replace_key` found for struct `hashbrown::hash_map::OccupiedEntry` in the current scope
  --> kube-runtime/src/scheduler.rs:90:27
   |
90 |                 old_entry.replace_key();
   |                           ^^^^^^^^^^^ method not found in `OccupiedEntry<'_, T, ScheduledEntry>`
```

as a result of them reworking their Entry api: https://github.com/rust-lang/hashbrown/pull/535

author there suggests the [entry_ref](https://docs.rs/hashbrown/latest/hashbrown/hash_map/struct.HashMap.html#method.entry_ref) api. looked at it for 1m and it didn't look immediately obvious so have left this issue here for now.

Need to update this usage here: https://github.com/kube-rs/kube/blob/62f95cd9a8506b639e01e10af417fecb7b45e292/kube-runtime/src/scheduler.rs#L81-L103
which makes us able to use the same hashbrown version everywhere (and we [can kill this instruction](https://github.com/kube-rs/kube/blob/main/deny.toml#L67-L69) with wrong comment)

**Comment by clux** [comment]
pushing this until next minor. if anyone wants to give it a go in the mean time, feel free;

```sh
cargo upgrade -p hashbrown -i
$EDITOR kube-runtime/src/scheduler.rs
```

afaikr the affected `scheduled` hashmap is of type `ObjectRef` -> `ScheduleRequest`
